server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址 lb loadbalance
          predicates: # 断言
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - After=2021-11-28T15:31:29.059+08:00[Asia/Shanghai]
            - Cookie=username,lc

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - Cookie=username,lc
#            - Header=X-Request-Id, \d+ # X-Request-Id属性并为整数的正则表达式
          filters:
            - AddRequestParameter=X-Request-ID,1024 #过网器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


